### ISSUE TITLE
tags.input: readonly vs disabled

### ISSUE THREAD

**Issue by metaleap** [vanjs-org/van#119]
I know this is a real edge-case but would be totally nice if one could pass to `van.tags.input({},...)` a `readonly: false` (typically, would be a terniary conditional rather than false const of course =) similar to `disabled`, without the readonly-ness becoming true in-the-browser (well, certainly Chromium).

Ie.: when we pass `{disabled:false}`, the input is not disabled, but passing `{readonly:false}` seems to make it readonly still.

I know full well that it's really a quirk of HTML and/or the browsers' DOM APIs rather than van's, of course ... and special-casing like that in a crisp codebase such as van might just be a no-go for you... but like I said, here's a "would be too neat from the van user's point-of-view"  =)  &mdash; feel free to close issue if out-of-scope or going against the van design philosophy or something.

Neat lib, glad it exists! Really happy to not have to go heavyweight overbloated React-and-the-likes and can stay vanilla, and appreciate the .d.ts too.

**Comment by Tao-VanJS** [comment]
Hi @metaleap,

Thanks for reaching out!

The DOM property name for `HTMLInputElement` is `readOnly` (note the case) instead of `readonly`, see: https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement.

Thus when you build something like `input({..., readonly: false})`, it's setting the "readonly" attribute via `setAttribute` (see the [property resolution rule](https://vanjs.org/advanced#dom-attributes-vs-properties)). And the presence of the `readonly` attribute (regardless of its value) will make the input element read-only. That's the reason why passing `{readonly:false}` still makes the element read only.

Hope it help :-)

**Comment by metaleap** [comment]
Whoa, nice gotcha! Missed that subtlety entirely, many thanks!
