### ISSUE TITLE
Error on when using method for Date data in VanX reactive (and possibly all class instance).

### ISSUE THREAD

**Issue by mintong89** [vanjs-org/van#255]
When I create a reactive object with Date object in it:
```js
const data = vanX.reactive({ date: new Date() })
```

If I calling a method from the date:
```js
console.log(data.date.toString())
```

It gives error of:
```
TypeError: Method Date.prototype.toString called on incompatible receiver [object Date]
```

How can I solve it? Thanks!

**Comment by LiquidAlmond** [comment]
Here's a grain of salt to go along with my analysis since I'm a noob.

It appears `reactive` converts class instances to an object consisting of just the public variables of the class. The root issue can be replicated with the following.
```javascript
class Test {
  #something;
  constructor(something) {
    this.#something = something;
  }
}
const test = new Test("something");
console.log(test.#something);
console.log(Object.entries(test));

// Check van.reactive({ test }) if you want
```

Conversing with ChatGPT has given a reasonable solution. We just need to change the `!(srcObj instanceof Object)` check in the reactive function to
```javascript
!(srcObj && srcObj.contructor === Object && getPrototypeOf(srcObj))
```

We can make this smaller if we ignore the case where srcObj is created with `Object.create(null)`. There may be other optimizations that I'm unaware of.

I believe this solution would make it so class instances are never reactive, but that seems to be the current state of affairs anyway.

**Comment by LiquidAlmond** [comment]
Well, my noobness was shining bright.

Seems the issue is more with how Date operates, specifically the value of `this` gets changed to the proxy instead of the Date object, which is what the functions in Date expect. Changing the get trap in the Proxy created in reactive to set the proper context on function calls might do the trick.

**Comment by Tao-VanJS** [comment]
See https://vanjs.org/x#caveat-native-reactivity.

**Comment by mintong89** [comment]
ok got it, I guess I'll stringify the date before inserting into state. Thanks.
