### ISSUE TITLE
Rename this Project from Van to anything else that doesn't have to do with vanilla javascript.

### ISSUE THREAD

**Issue by ibsusu** [vanjs-org/van#9]
This is not vanilla javascript and not even close to it.  The name is just confusing.  I hope you succeed but not as long as this repo has this name.

**Comment by donohoe** [comment]
If it’s worth saying, it’s worth saying twice; please drop the ‘vanilla’ reference in the project name. It creates nothing but confusion.

**Comment by NicolasCARPi** [comment]
Yeah, that is possibly the worst name for a javascript library, maybe just after `js`. If you thought it was a good idea to name your javascript library "vanilla", it is not. Very much so. So please consider rebranding as soon as possible!

**Comment by groovenectar** [comment]
After seeing the comments I too was thinking that perhaps the simplest route would be Van and just removing references to vanilla.

That said, I'm not the least bit offended by the name as it is, and in my opinion it's not confusing. The best case I can see for changing it is to avoid isolating users who can't get past the name. Which is apparently a thing.

Instead of only complaining about what to _not_ call it, perhaps offer some thoughts or suggestion for names? Since that is an effort in itself. If people who complain end up actually instigating a name change, here are 3 ideas: SmolJS, TopJS, LayerJS. Not sure if those are very active libraries already, but "Vanilla JS" (and also VanJS) is not likely used by another active library. Vanilla-js.com is simply a satirical website referring to the JavaScript language itself, which is not a JavaScript library. Further, this one is referred to as "VanJS" despite the expansion.

Might consider that it could be a "vocal minority" calling for a change, though this does seem to come on strong out of the gate. I'd be curious to know the ratio of people who particularly _like_ the current name with the context of the arguement. I'd have to say I'm one of them so far.

I'm immediately enthralled by this library and sincerely hope that no traces of discouragement come from the initial comments.

**Comment by zamadatix** [comment]
@groovenectar I think you may be missing the forest through the trees because of your overwhelming interest in dismissing the criticism. The issue isn't "vanilla-js.com, the satirical website" is using the name, rather, Vanilla JS is an industry wide term which refers to JS without any libraries. The project's own readme already contains confusing reference to this. The readme starts out saying VanJS is an abbreviation:

> VanJS (abbr. Vanilla JavaScript)

And later goes on to use the very term in the standard way:

> VanJS is a very thin layer on top of Vanilla JavaScript and DOM

You don't find other projects with the name because the name doesn't refer to a project, rather the language when used without a project. As far as bikeshedding on what the actual name should be, I agree with the others. It doesn't matter as much what the name is as long as it doesn't conflate with something referring to the language it's written in.

That said, if the maintainers need a pool of suggestions, then maybe something like icecream.js or neapolitan.js (dot optional). These allow the library to keep the ice cream theme and that it is a thin layer on top of Vanilla JavaScript. From a cursory search there don't seem to be any large, active, projects using these but if there are, again, the point isn't "it should be a unique, fantastic name" rather "it shouldn't be interchangeable with an existing language term".

**Comment by eddie-wrstbnd** [comment]
The name doesn't bother me too much, but I like coming up with names. What about calling it anilla.js? Potential tagline: "anilla.js so lite it is almost vAnilla".

**Comment by zamadatix** [comment]
> How likely is that to happen in reality? What's the biggest deal if it does? Does everyone really think this library is going to be "_the_ Vanilla JS"?

As mentioned, the first sentence of the readme starts out saying it's an abbreviated version of vanilla js so there is a short path to understanding how it can be confused. If the project only ever referred to itself as Van, which is one option this issue started with,, then, sure, it'd be unlikely to be confused. It's possible you genuinely don't see any of this as confusing, however, it's also clear a large number of others did in practice, not theory. Trying to argue others didn't actually find it confusing seems a bit brash in its own right.

anilla.js is clever. Or even just "nilla", so it's a bit easier to say.

**Comment by Tao-VanJS** [comment]
Thanks everyone for the great discussion! I appreciate the opinions from both sides.

VanJS is a non-profit project, with no plan on commercialization. As a result, I don't have a team working for it. Even for me, there is limited bandwidth in my spare time that I can contribute to it while having a full-time job. There is no sponsorship for the project, either.

Within my limited bandwidth, I would like to concentrate my energy to make VanJS helpful to as many people as possible, that includes improving the code, perfecting the tutorial and sample apps, and answering questions when anyone meets difficulties while coding with VanJS.

Thank you again for your interest in this project! Hope it can be helpful for you in some way. 😀

**Comment by zamadatix** [comment]
I'd be willing to donate $100 and some time to help get this issue resolved for users, if it would help.

**Comment by groovenectar** [comment]
Good point about infrastructure costs! Another reason to tone it down with demands. Really nice of @zamadatix to offer help on that front. Though of course there are other inconveniences associated with such a switch.

> Trying to argue others didn't actually find it confusing seems a bit brash in its own right.

I would argue that most everyone who is saying it's confusing are not saying it's confusing to _them_, they're arguing that other people besides them will be confused. I might be wrong about that but it seems pretty clear to me that no one has confused the VanJS framework for the ubiquitous JavaScript language based on any comments I've seen. Which, if true, is perhaps ironically a case for the side that it's technically not confusing?

**Comment by zamadatix** [comment]
The HN thread you later linked of has several comments along this line saying similar things such as "I also thought this was a 'joke' on how you don't need a framework. But looks like it is indeed a framework so definitely confusing name." Similarly, that's the very same confusion I had first viewing the project. I also commented on my confusion of the use of both meanings of "vanilla JS" in the readme. To me, the opening comment of this issue is along those lines, but maybe that's just my interpretation from having found the issue from the standpoint of being confused on the name.

Now, I can not guarantee every person here was confused vs was concerned others may be confused. What I can provide is something more relevant: a repetition that yes, in practice, people do find it confusing.

**Comment by groovenectar** [comment]
If you are new to JavaScript, what did you think after 10 minutes of research? Did you still think that it is confusing after 10 minutes? Should someone named "Steve" be mad at everyone else who is named "Steve" just because another "Steve" had a great idea? Further, the **brash** opening comment says "the name is just confusing" which says nothing about whether the author of that comment was themself confused or whether it was a "hivemind" reaction referring to the author of the comment or everyone else.

I propose that this project be renamed from VanJS to VanillaJS

**Comment by ArjixWasTaken** [comment]
> I would argue that most everyone who is saying it's confusing are not saying it's confusing to them, they're arguing that other people besides them will be confused. I might be wrong about that but it seems pretty clear to me that no one has confused the VanJS framework for the ubiquitous JavaScript language based on any comments I've seen. Which, if true, is perhaps ironically a case for the side that it's technically not confusing?

When Europeans say football, they mean soccer, when Americans say football, they mean American rugby.
If you know the other person is an American, you can understand that they actually meant rugby and not soccer.

If I tell an American that I am good at football, w/o any context they will think that I am talking about their football.
When context comes into play they can infer that I meant soccer.

But it obviously is confusing w/o context.
A newbie programmer or just a person new to JS in general, would not know what vanilla JS means, and if they find this repo then they will misunderstand what their senior told them to use.

**Comment by ArjixWasTaken** [comment]
https://github.com/vanjs-org
> An ultra-lightweight, zero-dependency, and unopinionated Reactive UI framework based on pure vanilla JavaScript and DOM.

From the context of your org description, you use vanilla to mean "just javascript, no native code".
At least that's what I would infer from it.

Of course that is not what you meant, you actually meant "zero dependency", but that is not the meaning you convey.
Libraries are not vanilla js, so the only meaning left would be about the language used to make the library.

React, Svelte, Angular, Vue and any kind of JS framework that doesn't use native code, is technically built using pure javascript.
So not only is it confusing to call your project vanilla, it is also wrong to call it vanilla.

If you meant zero-dependency, then say zero-dependency.
It is as simple as that.

You might have heard of JQuery, it has no dependencies, it only has dev dependencies.
Is JQuery vanilla js? No.

And everyone agrees on that.

**Comment by groovenectar** [comment]
I propose that this framework be renamed to "jQuery"

**Comment by groovenectar** [comment]
In all seriousness aside from the name is already wonderful... I asked GPT:

What are some variations of the word "Vanilla"?
Vanillic, Vanillin, Vanilloid, Vanillity, Vanillish, Vanillated, Vanillal, Vanille.

Make up a new word that starts with "van":
Vandoodle

Make up 5 new words that start with "van":
Vantrophy, Vancessor, Vantorque, Vanterlude, Vandorious.

And also about 60-80 words twice that start with or contain "van", most of which aren't considerable

My favorite other than the greatest and best (Vanilla) is "Vanillish" where "ish" implies some variation

But really the overall best move would be to rename it to "VanillaJS" from "VanJS"

Although "VanJS" is incredible, "VanillaJS" has that "ice cream" feel that you just don't get from "VanJS"

**Comment by rawoke083** [comment]
I find the name so off putting, I didn't even look at the code !

**Comment by rawoke083** [comment]
> In all seriousness aside from the name is already wonderful... I asked GPT:
> 
> What are some variations of the word "Vanilla"? Vanillic, Vanillin, Vanilloid, Vanillity, Vanillish, Vanillated, Vanillal, Vanille.
> 
> Make up a new word that starts with "van": Vandoodle
> 
> Make up 5 new words that start with "van": Vantrophy, Vancessor, Vantorque, Vanterlude, Vandorious.
> 
> And also about 60-80 words twice that start with or contain "van", most of which aren't considerable
> 
> My favorite other than the greatest and best (Vanilla) is "Vanillish" where "ish" implies some variation
> 
> But really the overall best move would be to rename it to "VanillaJS" from "VanJS"
> 
> Although "VanJS" is incredible, "VanillaJS" has that "ice cream" feel that you just don't get from "VanJS"

Are you serious ? 
After the big backlash and multiple sources of signals and feedback from community, you still want to try for a vanilla-like name ?? 
Wow !!!

**Comment by jchook** [comment]
This is an easy fix:

# 🚐 VanJS

**Comment by Tao-VanJS** [comment]
> This is an easy fix:
> 
> # 🚐 VanJS

Or 🚐💨 **VanJS**? 😁

**Comment by AndrewLamWARC** [comment]
Like @zamadatix, I'm also willing to contribute $100 towards infra costs. 
Unlike him, I'm not offended by the name. 
However, note that the name is a bit generic and it took me 3 google attempts to find this repo.

**Comment by Tao-VanJS** [comment]
Thanks @AndrewLamWARC for your offering. Out of curiosity, I'm wondering what keywords you are using to Google? It looks like "VanJS", "van js", "van.js" or even "lightweight reactive framework", "smallest reactive framework" can find https://vanjs.org/ or this repo well.

To be honest, renaming the project is very hard. Even if I can do all the logistics work of name changing, I can't ask all the tech bloggers and video makers to update their content. Thus people who heard VanJS from their sources will fail to find the project anyway.

So thanks for your understanding!

**Comment by sKopheK** [comment]
it's a bit confusing to say the least, but i will gladly agree with points of both sides. just drop vanilla from the homepage ("VanJS ([abbreviated Vanilla JavaScript](https://vanjs.org/about#name))") + other references and never mention it again - people will get over it, they always do :)

**Comment by groovenectar** [comment]
I'm also curious about the search keywords if VanJS was the target link to find

With both Startpage.com and Metager.org at the moment searching "VanJS" brings up the official site as the first result

A search for "VanillaJS" or "Vanilla JS" does not bring up the homepage at all. I would strongly doubt that there was ever any intention for it to come up via "VanillaJS" especially with deep knowledge about search engines, so the results seem as imagined and VanJS doesn't seem hard to find when that's specifically what you're looking for
